### ISSUE TITLE
Unable to locate element: {"method":"css selector","selector":"._3Tw1q"}

### ISSUE THREAD

**Issue by kannadivinorum** [eddyharrington/WhatSoup#1]
hello, i having a problem running it on Win

> C:\Windows\system32>python C:\Users\Kanna\WhatSoup\whatsoup.py
[9512:4340:0227/163848.421:ERROR:upgrade_util_win.cc(73)] IProcessLauncher::LaunchCmdElevated failed; hr = 80004002
[9512:2152:0227/163848.451:ERROR:login_database.cc(654)] Password store database is too new, kCurrentVersionNumber=28, GetCompatibleVersionNumber=29
[9512:2152:0227/163848.451:ERROR:password_store_default.cc(39)] Could not create/open login database.
DevTools listening on ws://127.0.0.1:55297/devtools/browser/6e5e80ed-295c-4c29-85e4-45131568fd88
Success! WhatsApp finished loading and is ready.
Traceback (most recent call last):
  File "C:\Users\Kanna\WhatSoup\whatsoup.py", line 1008, in <module>
    main()
  File "C:\Users\Kanna\WhatSoup\whatsoup.py", line 29, in main
    chats = get_chats(driver)
  File "C:\Users\Kanna\WhatSoup\whatsoup.py", line 183, in get_chats
    name_of_chat = selected_chat.find_element_by_class_name(
  File "C:\Users\Kanna\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webelement.py", line 398, in find_element_by_class_name
    return self.find_element(by=By.CLASS_NAME, value=name)
  File "C:\Users\Kanna\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webelement.py", line 658, in find_element
    return self._execute(Command.FIND_CHILD_ELEMENT,
  File "C:\Users\Kanna\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\Kanna\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Kanna\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"._3Tw1q"}
  (Session info: chrome=87.0.4280.66)

It opens chrome and opens WhatsApp web, but it does nothing to the page itself

**Comment by eddyharrington** [comment]
@kannadivinorum thanks for letting me know! I just pushed a change that should fix this. Can you do a `git pull`, try again, and let me know if you have any other issues? I've tested it on Win/Linux/Mac so you should be good to go.

To expand on the issue itself...before the most recent update, WhatSoup had a lot of hardcoded HTML attributes in place and in the case of your error it was a DIV element with class "_3Tw1q" which no longer exists, hence the message of 'no such element: Unable to locate element...' WhatsApp cycles and randomizes most of its HTML attributes which means an error like this will happen often if we keep using hardcoded values.

The fix replaced all hardcoded HTML attribute names with Xpath values and other means of identifying the right elements without depending on randomly generated and frequently changing values.

**Comment by kannadivinorum** [comment]
I run it, and it seems to be working, it no longer get that error, that fixed the issue!

However, when i try to export the chat, i get an "Error! 'Erika' produced no search results in WhatsApp." and i don't know if it has something to do with the same issue.

Full event: 

(env) PS C:\Windows\system32> python C:\Users\Kanna\WhatSoup\whatsoup.py_util_win.cc(73)] IProcessLauncher::LaunchCmdEle[11424:9604:0227/175057.160:ERROR:upgrade_util_win.cc(73)] IProcessLauncher::LaunchCmdElevated failed; hr = 80004002
[11424:10360:0227/175057.192:ERROR:login_database.cc(654)] Password store database is too new, kCurrentVersionNumber=28, GetCompatibleVersionNumber=29
[11424:10360:0227/175057.193:ERROR:password_store_default.cc(39)] Could not create/open login database.

DevTools listening on ws://127.0.0.1:56790/devtools/browser/7318812c-3898-4aee-aac1-f576ce33f505
Success! WhatsApp finished loading and is ready.
Success! Your chats have been loaded.
+-----------------------------------------------------------------------------------+
|                         Your 5 Most Recent WhatsApp Chats                         |
+---+--------------------+---------------+------------------------------------------+
| # | Chat Name          | Last Msg Time | Last Msg                                 |
+---+--------------------+---------------+------------------------------------------+
| 1 | Erika              | 5:17 p. m.    | Con tu familia? O andas sola? 😮         |
| 2 | Jonkis    | 5:01 p. m.    | Samuel: Sticker                          |
| 3 | impak      | ayer          | Hotaru: https://youtu.be/*********     |
| 4 | Ivan               | martes        | Deja les digo                            |
| 5 | +52 1 33 3973 4853 | lunes         | https://1fichier.com/**************** |
|   |                    |               | k0 esa es la ISO de 64 bits              |
+---+--------------------+---------------+------------------------------------------+

Would you like to see a complete summary of the scraped chats (y/n)? n

Select a chat export option.
  Options:
  chat number           Select chat for export
  -listchats            List your chats
  -quit                 Quit the application

What chat would you like to scrape and export? 1
Error! 'Erika' produced no search results in WhatsApp.

Select a chat export option.
  Options:
  chat number           Select chat for export
  -listchats            List your chats
  -quit                 Quit the application

What chat would you like to scrape and export?
________________________________________________________________________________________
Thank you for your fast respond by the way!

**Comment by kannadivinorum** [comment]
just to let you know, it seems to have something to do with the language, i changed my phone language to English and it's working like a charm! 

Again, thanks for the fast response!

**Comment by eddyharrington** [comment]
@kannadivinorum Glad you found a workaround. At the moment there are a few key elements in the HTML that I haven't found a great way to identify besides things like titles/labels which as you discovered are in English for me. For example, the code in question that produced your 2nd issue is:
```        
# Look for the unique class that holds 'Search results.'
WebDriverWait(driver, 5).until(expected_conditions.presence_of_element_located(
       (By.XPATH, "//*[@id='pane-side']/div[1]/div/div[contains(@aria-label,'Search results.')]")))
```

Thanks for letting me know you ran into this new issue. I'll create a new issue to track it and look into a better solution for the few elements that rely on English language settings. I'm closing this issue (hardcoded classes) for now.
