### ISSUE TITLE
Start script with an input argument to scrape only desired chat without loading up all users

### ISSUE THREAD

**Issue by ahrizvi** [eddyharrington/WhatSoup#5]
Hi, I was wondering if I could directly load a chat for desired user to scrape when I already know the name of person/group. I have a lot of old chats/groups etc and the scripts breakdown loading up the contacts mostly with exceptions

```
raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"span"}
  (Session info: chrome=90.0.4430.212)

```

**Comment by eddyharrington** [comment]
Hey there - sorry to say but this is no longer maintained and I'm unable to work on it anymore. Feel free to fork it and modify as necessary though.
